# fly.toml app configuration file generated for cors-anywhere-nq on 2025-01-15T20:56:07Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'cors-anywhere-nq'
primary_region = 'scl'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
